# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sts_combine_swift_objective_c' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
  pod 'Alamofire', '~> 4.7.2'
  pod 'SwiftyJSON', '~> 4.1.0'
  # Pods for sts_combine_swift_objective_c

end
